<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <Nullable>disable</Nullable>
    <LangVersion>9.0</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="unity/BattleNavigation/Assets/BattleNavigation/client/*.cs" />
    <Compile Include="generated/*.cs" />
    <Reference Include="FlyWow.Gateway"><HintPath>../unity/BattleNavigation/Assets/BattleNavigation/Plugins/FlyWow/FlyWow.Gateway.dll</HintPath></Reference>
    <Reference Include="Google.Protobuf"><HintPath>../unity/BattleNavigation/Assets/Plugins/Google.Protobuf.dll</HintPath></Reference>
    <Reference Include="BouncyCastle.Cryptography"><HintPath>../unity/BattleNavigation/Assets/BattleNavigation/Plugins/FlyWow/BouncyCastle.Cryptography.dll</HintPath></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>G:/Tuanjie/Editors/2022.3.62t12/Editor/Data/Managed/UnityEngine/UnityEngine.CoreModule.dll</HintPath></Reference>
    <Reference Include="UnityEngine.PhysicsModule"><HintPath>G:/Tuanjie/Editors/2022.3.62t12/Editor/Data/Managed/UnityEngine/UnityEngine.PhysicsModule.dll</HintPath></Reference>
    <Reference Include="UnityEngine.InputLegacyModule"><HintPath>G:/Tuanjie/Editors/2022.3.62t12/Editor/Data/Managed/UnityEngine/UnityEngine.InputLegacyModule.dll</HintPath></Reference>
    <Reference Include="UnityEngine.IMGUIModule"><HintPath>G:/Tuanjie/Editors/2022.3.62t12/Editor/Data/Managed/UnityEngine/UnityEngine.IMGUIModule.dll</HintPath></Reference>
  </ItemGroup>
</Project>
