// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: navigation_query.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Battle.Navigation.V1 {

  /// <summary>Holder for reflection information generated from navigation_query.proto</summary>
  public static partial class NavigationQueryReflection {

    #region Descriptor
    /// <summary>File descriptor for navigation_query.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static NavigationQueryReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZuYXZpZ2F0aW9uX3F1ZXJ5LnByb3RvEhRiYXR0bGUubmF2aWdhdGlvbi52",
            "MSJXCghFbnZlbG9wZRIYChBwcm90b2NvbF92ZXJzaW9uGAEgASgNEg8KB2Nv",
            "bW1hbmQYAiABKA0SEgoKcmVxdWVzdF9pZBgDIAEoBBIMCgRib2R5GAQgASgM",
            "IjkKDVdvcmxkUG9zaXRpb24SDAoEeF9tbRgBIAEoEhIMCgR5X21tGAIgASgS",
            "EgwKBHpfbW0YAyABKBIibgoQUXVlcnlDZWxsUmVxdWVzdBIOCgZtYXBfaWQY",
            "ASABKA0SEwoLbWFwX3ZlcnNpb24YAiABKA0SNQoIcG9zaXRpb24YAyABKAsy",
            "Iy5iYXR0bGUubmF2aWdhdGlvbi52MS5Xb3JsZFBvc2l0aW9uIowDChFRdWVy",
            "eUNlbGxSZXNwb25zZRJCCgZyZXN1bHQYASABKA4yMi5iYXR0bGUubmF2aWdh",
            "dGlvbi52MS5RdWVyeUNlbGxSZXNwb25zZS5SZXN1bHRDb2RlEg8KB21lc3Nh",
            "Z2UYAiABKAkSDgoGbWFwX2lkGAMgASgNEhMKC21hcF92ZXJzaW9uGAQgASgN",
            "Eg4KBmdyaWRfeBgFIAEoBRIOCgZncmlkX3oYBiABKAUSFgoOY2VsbF9oZWln",
            "aHRfbW0YByABKAUSDAoEYXJlYRgIIAEoDRIRCgljbGVhcmFuY2UYCSABKA0i",
            "owEKClJlc3VsdENvZGUSFgoSUkVTVUxUX1VOU1BFQ0lGSUVEEAASBgoCT0sQ",
            "ARIRCg1NQVBfTk9UX0ZPVU5EEAISGAoUTUFQX1ZFUlNJT05fTUlTTUFUQ0gQ",
            "AxIRCg1PVVRfT0ZfQk9VTkRTEAQSEAoMTk9UX1dBTEtBQkxFEAUSDwoLQkFE",
            "X1JFUVVFU1QQBhISCg5JTlRFUk5BTF9FUlJPUhAHYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Battle.Navigation.V1.Envelope), global::Battle.Navigation.V1.Envelope.Parser, new[]{ "ProtocolVersion", "Command", "RequestId", "Body" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Battle.Navigation.V1.WorldPosition), global::Battle.Navigation.V1.WorldPosition.Parser, new[]{ "XMm", "YMm", "ZMm" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Battle.Navigation.V1.QueryCellRequest), global::Battle.Navigation.V1.QueryCellRequest.Parser, new[]{ "MapId", "MapVersion", "Position" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Battle.Navigation.V1.QueryCellResponse), global::Battle.Navigation.V1.QueryCellResponse.Parser, new[]{ "Result", "Message", "MapId", "MapVersion", "GridX", "GridZ", "CellHeightMm", "Area", "Clearance" }, null, new[]{ typeof(global::Battle.Navigation.V1.QueryCellResponse.Types.ResultCode) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Envelope : pb::IMessage<Envelope>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Envelope> _parser = new pb::MessageParser<Envelope>(() => new Envelope());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Envelope> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Battle.Navigation.V1.NavigationQueryReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Envelope() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Envelope(Envelope other) : this() {
      protocolVersion_ = other.protocolVersion_;
      command_ = other.command_;
      requestId_ = other.requestId_;
      body_ = other.body_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Envelope Clone() {
      return new Envelope(this);
    }

    /// <summary>Field number for the "protocol_version" field.</summary>
    public const int ProtocolVersionFieldNumber = 1;
    private uint protocolVersion_;
    /// <summary>
    /// 线协议兼容边界版本。
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ProtocolVersion {
      get { return protocolVersion_; }
      set {
        protocolVersion_ = value;
      }
    }

    /// <summary>Field number for the "command" field.</summary>
    public const int CommandFieldNumber = 2;
    private uint command_;
    /// <summary>
    /// body 的业务消息类型；QueryCell 固定为 1001。
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Command {
      get { return command_; }
      set {
        command_ = value;
      }
    }

    /// <summary>Field number for the "request_id" field.</summary>
    public const int RequestIdFieldNumber = 3;
    private ulong requestId_;
    /// <summary>
    /// 请求/响应关联 ID；服务端原样返回。
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong RequestId {
      get { return requestId_; }
      set {
        requestId_ = value;
      }
    }

    /// <summary>Field number for the "body" field.</summary>
    public const int BodyFieldNumber = 4;
    private pb::ByteString body_ = pb::ByteString.Empty;
    /// <summary>
    /// command 对应消息的 Protobuf bytes。
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Body {
      get { return body_; }
      set {
        body_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Envelope);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Envelope other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ProtocolVersion != other.ProtocolVersion) return false;
      if (Command != other.Command) return false;
      if (RequestId != other.RequestId) return false;
      if (Body != other.Body) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ProtocolVersion != 0) hash ^= ProtocolVersion.GetHashCode();
      if (Command != 0) hash ^= Command.GetHashCode();
      if (RequestId != 0UL) hash ^= RequestId.GetHashCode();
      if (Body.Length != 0) hash ^= Body.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ProtocolVersion != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(ProtocolVersion);
      }
      if (Command != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Command);
      }
      if (RequestId != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(RequestId);
      }
      if (Body.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(Body);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ProtocolVersion != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(ProtocolVersion);
      }
      if (Command != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Command);
      }
      if (RequestId != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(RequestId);
      }
      if (Body.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(Body);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ProtocolVersion != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ProtocolVersion);
      }
      if (Command != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Command);
      }
      if (RequestId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(RequestId);
      }
      if (Body.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Body);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Envelope other) {
      if (other == null) {
        return;
      }
      if (other.ProtocolVersion != 0) {
        ProtocolVersion = other.ProtocolVersion;
      }
      if (other.Command != 0) {
        Command = other.Command;
      }
      if (other.RequestId != 0UL) {
        RequestId = other.RequestId;
      }
      if (other.Body.Length != 0) {
        Body = other.Body;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ProtocolVersion = input.ReadUInt32();
            break;
          }
          case 16: {
            Command = input.ReadUInt32();
            break;
          }
          case 24: {
            RequestId = input.ReadUInt64();
            break;
          }
          case 34: {
            Body = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ProtocolVersion = input.ReadUInt32();
            break;
          }
          case 16: {
            Command = input.ReadUInt32();
            break;
          }
          case 24: {
            RequestId = input.ReadUInt64();
            break;
          }
          case 34: {
            Body = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class WorldPosition : pb::IMessage<WorldPosition>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WorldPosition> _parser = new pb::MessageParser<WorldPosition>(() => new WorldPosition());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WorldPosition> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Battle.Navigation.V1.NavigationQueryReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorldPosition() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorldPosition(WorldPosition other) : this() {
      xMm_ = other.xMm_;
      yMm_ = other.yMm_;
      zMm_ = other.zMm_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorldPosition Clone() {
      return new WorldPosition(this);
    }

    /// <summary>Field number for the "x_mm" field.</summary>
    public const int XMmFieldNumber = 1;
    private long xMm_;
    /// <summary>
    /// 世界 X，毫米；负数合法，ZigZag 编码负值。
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long XMm {
      get { return xMm_; }
      set {
        xMm_ = value;
      }
    }

    /// <summary>Field number for the "y_mm" field.</summary>
    public const int YMmFieldNumber = 2;
    private long yMm_;
    /// <summary>
    /// 世界高度 Y，毫米；ZigZag 编码。
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long YMm {
      get { return yMm_; }
      set {
        yMm_ = value;
      }
    }

    /// <summary>Field number for the "z_mm" field.</summary>
    public const int ZMmFieldNumber = 3;
    private long zMm_;
    /// <summary>
    /// 世界 Z，毫米；负数合法，ZigZag 编码负值。
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ZMm {
      get { return zMm_; }
      set {
        zMm_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WorldPosition);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WorldPosition other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (XMm != other.XMm) return false;
      if (YMm != other.YMm) return false;
      if (ZMm != other.ZMm) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (XMm != 0L) hash ^= XMm.GetHashCode();
      if (YMm != 0L) hash ^= YMm.GetHashCode();
      if (ZMm != 0L) hash ^= ZMm.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (XMm != 0L) {
        output.WriteRawTag(8);
        output.WriteSInt64(XMm);
      }
      if (YMm != 0L) {
        output.WriteRawTag(16);
        output.WriteSInt64(YMm);
      }
      if (ZMm != 0L) {
        output.WriteRawTag(24);
        output.WriteSInt64(ZMm);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (XMm != 0L) {
        output.WriteRawTag(8);
        output.WriteSInt64(XMm);
      }
      if (YMm != 0L) {
        output.WriteRawTag(16);
        output.WriteSInt64(YMm);
      }
      if (ZMm != 0L) {
        output.WriteRawTag(24);
        output.WriteSInt64(ZMm);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (XMm != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(XMm);
      }
      if (YMm != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(YMm);
      }
      if (ZMm != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(ZMm);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WorldPosition other) {
      if (other == null) {
        return;
      }
      if (other.XMm != 0L) {
        XMm = other.XMm;
      }
      if (other.YMm != 0L) {
        YMm = other.YMm;
      }
      if (other.ZMm != 0L) {
        ZMm = other.ZMm;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            XMm = input.ReadSInt64();
            break;
          }
          case 16: {
            YMm = input.ReadSInt64();
            break;
          }
          case 24: {
            ZMm = input.ReadSInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            XMm = input.ReadSInt64();
            break;
          }
          case 16: {
            YMm = input.ReadSInt64();
            break;
          }
          case 24: {
            ZMm = input.ReadSInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class QueryCellRequest : pb::IMessage<QueryCellRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<QueryCellRequest> _parser = new pb::MessageParser<QueryCellRequest>(() => new QueryCellRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<QueryCellRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Battle.Navigation.V1.NavigationQueryReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QueryCellRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QueryCellRequest(QueryCellRequest other) : this() {
      mapId_ = other.mapId_;
      mapVersion_ = other.mapVersion_;
      position_ = other.position_ != null ? other.position_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QueryCellRequest Clone() {
      return new QueryCellRequest(this);
    }

    /// <summary>Field number for the "map_id" field.</summary>
    public const int MapIdFieldNumber = 1;
    private uint mapId_;
    /// <summary>
    /// BMAP Header 中的业务地图 ID；必须大于 0。
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MapId {
      get { return mapId_; }
      set {
        mapId_ = value;
      }
    }

    /// <summary>Field number for the "map_version" field.</summary>
    public const int MapVersionFieldNumber = 2;
    private uint mapVersion_;
    /// <summary>
    /// 客户端期望查询的地图资产版本。
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MapVersion {
      get { return mapVersion_; }
      set {
        mapVersion_ = value;
      }
    }

    /// <summary>Field number for the "position" field.</summary>
    public const int PositionFieldNumber = 3;
    private global::Battle.Navigation.V1.WorldPosition position_;
    /// <summary>
    /// 待查询的正式业务世界坐标。
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Battle.Navigation.V1.WorldPosition Position {
      get { return position_; }
      set {
        position_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as QueryCellRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(QueryCellRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MapId != other.MapId) return false;
      if (MapVersion != other.MapVersion) return false;
      if (!object.Equals(Position, other.Position)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MapId != 0) hash ^= MapId.GetHashCode();
      if (MapVersion != 0) hash ^= MapVersion.GetHashCode();
      if (position_ != null) hash ^= Position.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MapId != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(MapId);
      }
      if (MapVersion != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(MapVersion);
      }
      if (position_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Position);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MapId != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(MapId);
      }
      if (MapVersion != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(MapVersion);
      }
      if (position_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Position);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MapId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MapId);
      }
      if (MapVersion != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MapVersion);
      }
      if (position_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Position);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(QueryCellRequest other) {
      if (other == null) {
        return;
      }
      if (other.MapId != 0) {
        MapId = other.MapId;
      }
      if (other.MapVersion != 0) {
        MapVersion = other.MapVersion;
      }
      if (other.position_ != null) {
        if (position_ == null) {
          Position = new global::Battle.Navigation.V1.WorldPosition();
        }
        Position.MergeFrom(other.Position);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MapId = input.ReadUInt32();
            break;
          }
          case 16: {
            MapVersion = input.ReadUInt32();
            break;
          }
          case 26: {
            if (position_ == null) {
              Position = new global::Battle.Navigation.V1.WorldPosition();
            }
            input.ReadMessage(Position);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MapId = input.ReadUInt32();
            break;
          }
          case 16: {
            MapVersion = input.ReadUInt32();
            break;
          }
          case 26: {
            if (position_ == null) {
              Position = new global::Battle.Navigation.V1.WorldPosition();
            }
            input.ReadMessage(Position);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class QueryCellResponse : pb::IMessage<QueryCellResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<QueryCellResponse> _parser = new pb::MessageParser<QueryCellResponse>(() => new QueryCellResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<QueryCellResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Battle.Navigation.V1.NavigationQueryReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QueryCellResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QueryCellResponse(QueryCellResponse other) : this() {
      result_ = other.result_;
      message_ = other.message_;
      mapId_ = other.mapId_;
      mapVersion_ = other.mapVersion_;
      gridX_ = other.gridX_;
      gridZ_ = other.gridZ_;
      cellHeightMm_ = other.cellHeightMm_;
      area_ = other.area_;
      clearance_ = other.clearance_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QueryCellResponse Clone() {
      return new QueryCellResponse(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private global::Battle.Navigation.V1.QueryCellResponse.Types.ResultCode result_ = global::Battle.Navigation.V1.QueryCellResponse.Types.ResultCode.ResultUnspecified;
    /// <summary>
    /// 稳定机器结果码；客户端不得按 message 分支。
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Battle.Navigation.V1.QueryCellResponse.Types.ResultCode Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 2;
    private string message_ = "";
    /// <summary>
    /// 面向日志和调试的诊断文字。
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "map_id" field.</summary>
    public const int MapIdFieldNumber = 3;
    private uint mapId_;
    /// <summary>
    /// 实际接受查询的地图 ID。
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MapId {
      get { return mapId_; }
      set {
        mapId_ = value;
      }
    }

    /// <summary>Field number for the "map_version" field.</summary>
    public const int MapVersionFieldNumber = 4;
    private uint mapVersion_;
    /// <summary>
    /// 实际接受查询的地图资产版本。
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MapVersion {
      get { return mapVersion_; }
      set {
        mapVersion_ = value;
      }
    }

    /// <summary>Field number for the "grid_x" field.</summary>
    public const int GridXFieldNumber = 5;
    private int gridX_;
    /// <summary>
    /// 调试结果：地图内 X 列下标。
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int GridX {
      get { return gridX_; }
      set {
        gridX_ = value;
      }
    }

    /// <summary>Field number for the "grid_z" field.</summary>
    public const int GridZFieldNumber = 6;
    private int gridZ_;
    /// <summary>
    /// 调试结果：地图内 Z 行下标。
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int GridZ {
      get { return gridZ_; }
      set {
        gridZ_ = value;
      }
    }

    /// <summary>Field number for the "cell_height_mm" field.</summary>
    public const int CellHeightMmFieldNumber = 7;
    private int cellHeightMm_;
    /// <summary>
    /// Cell 地表世界 Y，毫米。
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CellHeightMm {
      get { return cellHeightMm_; }
      set {
        cellHeightMm_ = value;
      }
    }

    /// <summary>Field number for the "area" field.</summary>
    public const int AreaFieldNumber = 8;
    private uint area_;
    /// <summary>
    /// 稳定 BattleArea 编码。
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Area {
      get { return area_; }
      set {
        area_ = value;
      }
    }

    /// <summary>Field number for the "clearance" field.</summary>
    public const int ClearanceFieldNumber = 9;
    private uint clearance_;
    /// <summary>
    /// 到静态障碍/边界的距离，单位 Cell。
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Clearance {
      get { return clearance_; }
      set {
        clearance_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as QueryCellResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(QueryCellResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      if (Message != other.Message) return false;
      if (MapId != other.MapId) return false;
      if (MapVersion != other.MapVersion) return false;
      if (GridX != other.GridX) return false;
      if (GridZ != other.GridZ) return false;
      if (CellHeightMm != other.CellHeightMm) return false;
      if (Area != other.Area) return false;
      if (Clearance != other.Clearance) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != global::Battle.Navigation.V1.QueryCellResponse.Types.ResultCode.ResultUnspecified) hash ^= Result.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (MapId != 0) hash ^= MapId.GetHashCode();
      if (MapVersion != 0) hash ^= MapVersion.GetHashCode();
      if (GridX != 0) hash ^= GridX.GetHashCode();
      if (GridZ != 0) hash ^= GridZ.GetHashCode();
      if (CellHeightMm != 0) hash ^= CellHeightMm.GetHashCode();
      if (Area != 0) hash ^= Area.GetHashCode();
      if (Clearance != 0) hash ^= Clearance.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Result != global::Battle.Navigation.V1.QueryCellResponse.Types.ResultCode.ResultUnspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Message);
      }
      if (MapId != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(MapId);
      }
      if (MapVersion != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(MapVersion);
      }
      if (GridX != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(GridX);
      }
      if (GridZ != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(GridZ);
      }
      if (CellHeightMm != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(CellHeightMm);
      }
      if (Area != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(Area);
      }
      if (Clearance != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(Clearance);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Result != global::Battle.Navigation.V1.QueryCellResponse.Types.ResultCode.ResultUnspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Message);
      }
      if (MapId != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(MapId);
      }
      if (MapVersion != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(MapVersion);
      }
      if (GridX != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(GridX);
      }
      if (GridZ != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(GridZ);
      }
      if (CellHeightMm != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(CellHeightMm);
      }
      if (Area != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(Area);
      }
      if (Clearance != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(Clearance);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Result != global::Battle.Navigation.V1.QueryCellResponse.Types.ResultCode.ResultUnspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (MapId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MapId);
      }
      if (MapVersion != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MapVersion);
      }
      if (GridX != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GridX);
      }
      if (GridZ != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GridZ);
      }
      if (CellHeightMm != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CellHeightMm);
      }
      if (Area != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Area);
      }
      if (Clearance != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Clearance);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(QueryCellResponse other) {
      if (other == null) {
        return;
      }
      if (other.Result != global::Battle.Navigation.V1.QueryCellResponse.Types.ResultCode.ResultUnspecified) {
        Result = other.Result;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      if (other.MapId != 0) {
        MapId = other.MapId;
      }
      if (other.MapVersion != 0) {
        MapVersion = other.MapVersion;
      }
      if (other.GridX != 0) {
        GridX = other.GridX;
      }
      if (other.GridZ != 0) {
        GridZ = other.GridZ;
      }
      if (other.CellHeightMm != 0) {
        CellHeightMm = other.CellHeightMm;
      }
      if (other.Area != 0) {
        Area = other.Area;
      }
      if (other.Clearance != 0) {
        Clearance = other.Clearance;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Result = (global::Battle.Navigation.V1.QueryCellResponse.Types.ResultCode) input.ReadEnum();
            break;
          }
          case 18: {
            Message = input.ReadString();
            break;
          }
          case 24: {
            MapId = input.ReadUInt32();
            break;
          }
          case 32: {
            MapVersion = input.ReadUInt32();
            break;
          }
          case 40: {
            GridX = input.ReadInt32();
            break;
          }
          case 48: {
            GridZ = input.ReadInt32();
            break;
          }
          case 56: {
            CellHeightMm = input.ReadInt32();
            break;
          }
          case 64: {
            Area = input.ReadUInt32();
            break;
          }
          case 72: {
            Clearance = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Result = (global::Battle.Navigation.V1.QueryCellResponse.Types.ResultCode) input.ReadEnum();
            break;
          }
          case 18: {
            Message = input.ReadString();
            break;
          }
          case 24: {
            MapId = input.ReadUInt32();
            break;
          }
          case 32: {
            MapVersion = input.ReadUInt32();
            break;
          }
          case 40: {
            GridX = input.ReadInt32();
            break;
          }
          case 48: {
            GridZ = input.ReadInt32();
            break;
          }
          case 56: {
            CellHeightMm = input.ReadInt32();
            break;
          }
          case 64: {
            Area = input.ReadUInt32();
            break;
          }
          case 72: {
            Clearance = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the QueryCellResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum ResultCode {
        [pbr::OriginalName("RESULT_UNSPECIFIED")] ResultUnspecified = 0,
        [pbr::OriginalName("OK")] Ok = 1,
        [pbr::OriginalName("MAP_NOT_FOUND")] MapNotFound = 2,
        [pbr::OriginalName("MAP_VERSION_MISMATCH")] MapVersionMismatch = 3,
        [pbr::OriginalName("OUT_OF_BOUNDS")] OutOfBounds = 4,
        [pbr::OriginalName("NOT_WALKABLE")] NotWalkable = 5,
        [pbr::OriginalName("BAD_REQUEST")] BadRequest = 6,
        [pbr::OriginalName("INTERNAL_ERROR")] InternalError = 7,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
